apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.PORT | default "3000" | quote }}
  NODE_ENV: {{ .Values.config.NODE_ENV | default "production" | quote }}