apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontend.fullname" . }}-secrets
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
type: Opaque
data:
  next_public_cohere_api_key: {{ .Values.secrets.next_public_cohere_api_key | b64enc | quote }}
  next_public_better_auth_secret: {{ .Values.secrets.next_public_better_auth_secret | b64enc | quote }}